name = "cf-subscription-aggregator"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
usage_model = "bundled"

# KV命名空间绑定
kv_namespaces = [
  { binding = "SUB_STORE", id = "your-kv-namespace-id" }
]

# 部署配置
[env.production]
workers_dev = true
zone_id = "your-zone-id"
account_id = "your-account-id"

# 自定义域（可选）
routes = [
  { pattern = "sub.yourdomain.com", custom_domain = true }
]

# 环境变量
vars = { 
  SUB_CONVERT_API = "https://sub.xf.free.hr",
  DEFAULT_TOKEN = "auto" 
}
